In [10]:
import pandas as pd
import numpy as np
import sklearn as sk

In [11]:
order_list = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - OrderList.csv', sep=',', encoding='ISO-8859-1')
freight_rates = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - FreightRates.csv', sep=',', encoding='ISO-8859-1')
wh_costs = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - WhCosts.csv', sep=',', encoding='ISO-8859-1')
wh_capacities = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - WhCapacities.csv', sep=',', encoding='ISO-8859-1')
products_per_plant = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - ProductsPerPlant.csv', sep=',', encoding='ISO-8859-1')
vmi_customers = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - VmiCustomers.csv', sep=',', encoding='ISO-8859-1')
plant_ports = pd.read_csv(r'C:\Users\mattt\Documents\Spring 2024\STAT 4188\shipping_project\Dataset\Supply chain logisitcs problem - PlantPorts.csv', sep=',', encoding='ISO-8859-1')

In [12]:
order_list.head()

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID,Plant Code,Destination Port,Unit quantity,Weight
0,1447296447,5/26/2013,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30
1,1447158015,5/26/2013,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94
2,1447138899,5/26/2013,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20
3,1447363528,5/26/2013,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16
4,1447363981,5/26/2013,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34

In [13]:
Right_join = pd.merge(order_list,  
                      products_per_plant,  
                      on ='Product ID', 
                      how ='right')

In [14]:
Right_join.head(20)

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID,Plant Code_x,Destination Port,Unit quantity,Weight,Plant Code_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1698815,NaN,NaN,NaN,NaN,PLANT15
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1664419,NaN,NaN,NaN,NaN,PLANT17
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1664426,NaN,NaN,NaN,NaN,PLANT17
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1672826,NaN,NaN,NaN,NaN,PLANT17
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1674916,NaN,NaN,NaN,NaN,PLANT17
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1674918,NaN,NaN,NaN,NaN,PLANT17
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1675507,NaN,NaN,NaN,NaN,PLANT17
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1676151,NaN,NaN,NaN,NaN,PLANT17
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1676152,NaN,NaN,NaN,NaN,PLANT17
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1677864,NaN,NaN,NaN,NaN,PLANT17
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1677865,NaN,NaN,NaN,NaN,PLANT17
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1679124,NaN,NaN,NaN,NaN,PLANT17
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1685369,NaN,NaN,NaN,NaN,PLANT17
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1685370,NaN,NaN,NaN,NaN,PLANT17
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1685378,NaN,NaN,NaN,NaN,PLANT17
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1685979,NaN,NaN,NaN,NaN,PLANT17
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1691969,NaN,NaN,NaN,NaN,PLANT17
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1694139,NaN,NaN,NaN,NaN,PLANT17
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1694217,NaN,NaN,NaN,NaN,PLANT17
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1696107,NaN,NaN,NaN,NaN,PLANT17

In [15]:
Right_join = Right_join.dropna(axis = 0)

In [16]:
Right_join.head()

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID,Plant Code_x,Destination Port,Unit quantity,Weight,Plant Code_y
23,1.447184e+09,5/26/2013,PORT04,V444_0,2.0,DTP,0.0,0.0,V5555555555_1,1666994,PLANT12,PORT09,318.0,1.109599,PLANT18
24,1.447265e+09,5/26/2013,PORT04,V444_0,2.0,DTP,3.0,0.0,V55555555_5,1666994,PLANT12,PORT09,237.0,1.109599,PLANT18
25,1.447306e+09,5/26/2013,PORT04,V444_0,2.0,DTP,3.0,0.0,V55555555_5,1666994,PLANT12,PORT09,432.0,75.904743,PLANT18
26,1.447225e+09,5/26/2013,PORT04,V444_0,2.0,DTP,0.0,0.0,V55555555_5,1666994,PLANT12,PORT09,517.0,119.959909,PLANT18
27,1.447323e+09,5/26/2013,PORT04,V444_0,2.0,DTP,0.0,0.0,V55555555_5,1666994,PLANT12,PORT09,947.0,325.955307,PLANT18

In [17]:
join_products_plants = pd.merge(products_per_plant, plant_ports, on = 'Plant Code', how = 'right')

In [18]:
join_products_plants.head()

  Plant Code  Product ID    Port
0    PLANT01   1654431.0  PORT01
1    PLANT01   1664406.0  PORT01
2    PLANT01   1664416.0  PORT01
3    PLANT01   1665542.0  PORT01
4    PLANT01   1665863.0  PORT01

In [19]:
join_all = pd.merge(order_list, join_products_plants, on = 'Plant Code', how = 'right')

In [20]:
join_all = join_all.dropna(axis = 0)

In [21]:
join_all.head(10)

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID_x,Plant Code,Destination Port,Unit quantity,Weight,Product ID_y,Port
556,1.447307e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699333.0,PLANT03,PORT09,1529.0,3.008251,1613321.0,PORT04
557,1.447307e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699268.0,PLANT03,PORT09,1495.0,2.653360,1613321.0,PORT04
558,1.447393e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699268.0,PLANT03,PORT09,899.0,1.326680,1613321.0,PORT04
559,1.447307e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699268.0,PLANT03,PORT09,1437.0,2.653360,1613321.0,PORT04
560,1.447190e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699584.0,PLANT03,PORT09,1914.0,5.940000,1613321.0,PORT04
561,1.447190e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699584.0,PLANT03,PORT09,1956.0,5.940000,1613321.0,PORT04
562,1.447190e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699584.0,PLANT03,PORT09,1964.0,5.940000,1613321.0,PORT04
563,1.447406e+09,5/26/2013,PORT04,V44_3,0.0,CRF,0.0,0.0,V555555555555555_29,1699584.0,PLANT03,PORT09,1961.0,5.940000,1613321.0,PORT04
564,1.447307e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699584.0,PLANT03,PORT09,3624.0,11.820000,1613321.0,PORT04
565,1.447182e+09,5/26/2013,PORT04,V44_3,4.0,CRF,0.0,0.0,V555555555555555_29,1699562.0,PLANT03,PORT09,4802.0,8.892328,1613321.0,PORT04

In [22]:
order_ports = []
order_id = []

for i in range (0, join_all.shape[0]):
    order_id.append(join_all['Order ID'].loc[join_all.index[i]])

In [23]:
order_id

[1447306623.0,
 1447306542.0,
 1447392841.0,
 1447306544.0,
 1447189596.0,
 1447189595.0,
 1447189594.0,
 1447405924.0,
 1447306545.0,
 1447182455.0,
 1447320770.0,
 1447317000.0,
 1447320724.0,
 1447306568.0,
 1447306638.0,
 1447399897.0,
 1447306541.0,
 1447306622.0,
 1447320842.0,
 1447399895.0,
 1447320824.0,
 1447418501.0,
 1447379298.0,
 1447269469.0,
 1447379326.0,
 1447269471.0,
 1447182454.0,
 1447379202.0,
 1447344846.0,
 1447412853.0,
 1447313127.0,
 1447320656.0,
 1447269470.0,
 1447182459.0,
 1447182461.0,
 1447410409.0,
 1447306546.0,
 1447403804.0,
 1447392327.0,
 1447392329.0,
 1447392328.0,
 1447320843.0,
 1447379299.0,
 1447399896.0,
 1447355126.0,
 1447379325.0,
 1447182475.0,
 1447182479.0,
 1447320825.0,
 1447405963.0,
 1447320802.0,
 1447306593.0,
 1447306625.0,
 1447405948.0,
 1447182482.0,
 1447405955.0,
 1447325922.0,
 1447182469.0,
 1447392876.0,
 1447325914.0,
 1447325916.0,
 1447269587.0,
 1447182481.0,
 1447406047.0,
 1447242979.0,
 1447340138.0,
 1447252497.0,
 1447340137.0,
 1447182464.0,
 1447405956.0,
 1447405946.0,
 1447365155.0,
 1447405962.0,
 1447316993.0,
 1447340136.0,
 1447331106.0,
 1447182477.0,
 1447325827.0,
 1447325826.0,
 1447320841.0,
 1447399894.0,
 1447405987.0,
 1447320771.0,
 1447182456.0,
 1447320772.0,
 1447327176.0,
 1447386266.0,
 1447306632.0,
 1447392848.0,
 1447182466.0,
 1447254155.0,
 1447392832.0,
 1447316604.0,
 1447182473.0,
 1447392846.0,
 1447182474.0,
 1447241594.0,
 1447392847.0,
 1447392833.0,
 1447182480.0,
 1447405934.0,
 1447182471.0,
 1447344845.0,
 1447412852.0,
 1447182468.0,
 1447182458.0,
 1447313125.0,
 1447405947.0,
 1447344844.0,
 1447182467.0,
 1447313124.0,
 1447182457.0,
 1447313126.0,
 1447306599.0,
 1447306598.0,
 1447343378.0,
 1447306540.0,
 1447306543.0,
 1447350176.0,
 1447397994.0,
 1447231068.0,
 1447306539.0,
 1447355122.0,
 1447240888.0,
 1447364832.0,
 1447240889.0,
 1447306547.0,
 1447372032.0,
 1447298091.0,
 1447182462.0,
 1447320773.0,
 1447405933.0,
 1447182478.0,
 1447182470.0,
 1447387682.0,
 1447182465.0,
 1447405925.0,
 1447320725.0,
 1447286437.0,
 1447189588.0,
 1447231071.0,
 1447182463.0,
 1447337605.0,
 1447344825.0,
 1447182453.0,
 1447327230.0,
 1447182472.0,
 1447182476.0,
 1447377331.0,
 1447306550.0,
 1447320801.0,
 1447377332.0,
 1447286434.0,
 1447286433.0,
 1447366430.0,
 1447320823.0,
 1447405949.0,
 1447182452.0,
 1447306624.0,
 1447262012.0,
 1447308835.0,
 1447261867.0,
 1447201701.0,
 1447356153.0,
 1447338332.0,
 1447308150.0,
 1447335437.0,
 1447262050.0,
 1447261869.0,
 1447404340.0,
 1447323414.0,
 1447384151.0,
 1447221634.0,
 1447340633.0,
 1447184596.0,
 1447278500.0,
 1447386297.0,
 1447182392.0,
 1447309255.0,
 1447396767.0,
 1447352019.0,
 1447352021.0,
 1447379197.0,
 1447359555.0,
 1447178244.0,
 1447317148.0,
 1447359554.0,
 1447352022.0,
 1447352018.0,
 1447352020.0,
 1447205762.0,
 1447205763.0,
 1447370682.0,
 1447372963.0,
 1447182403.0,
 1447234949.0,
 1447178062.0,
 1447388729.0,
 1447392217.0,
 1447193187.0,
 1447353695.0,
 1447352524.0,
 1447182398.0,
 1447278497.0,
 1447255584.0,
 1447332136.0,
 1447366887.0,
 1447234950.0,
 1447213261.0,
 1447201702.0,
 1447201700.0,
 1447182394.0,
 1447178243.0,
 1447182393.0,
 1447362579.0,
 1447410884.0,
 1447373506.0,
 1447393109.0,
 1447205898.0,
 1447261157.0,
 1447283772.0,
 1447216710.0,
 1447302786.0,
 1447283727.0,
 1447373433.0,
 1447389131.0,
 1447208346.0,
 1447266883.0,
 1447373503.0,
 1447401850.0,
 1447373491.0,
 1447373510.0,
 1447305018.0,
 1447373481.0,
 1447305017.0,
 1447373453.0,
 1447186295.0,
 1447201982.0,
 1447219347.0,
 1447186299.0,
 1447186296.0,
 1447201983.0,
 1447201985.0,
 1447219348.0,
 1447302857.0,
 1447373488.0,
 1447399142.0,
 1447373487.0,
 1447399141.0,
 1447373486.0,
 1447373464.0,
 1447219344.0,
 1447373480.0,
 1447373479.0,
 1447305011.0,
 1447402615.0,
 1447402565.0,
 1447402566.0,
 1447312218.0,
 1447309077.0,
 1447403222.0,
 1447403221.0,
 1447373476.0,
 1447179686.0,
 1447373461.0,
 1447373421.0,
 1447306774.0,
 1447309551.0,
 1447390885.0,
 1447375215.0,
 1447301467.0,
 1447229098.0,
 1447392971.0,
 1447373492.0,
 1447390899.0,
 1447390908.0,
 1447367647.0,
 1447375240.0,
 1447312217.0,
 1447312216.0,
 1447188612.0,
 1447401851.0,
 1447309076.0,
 1447373505.0,
 1447390890.0,
 1447390889.0,
 1447309594.0,
 1447410883.0,
 1447390891.0,
 1447410885.0,
 1447241521.0,
 1447241523.0,
 1447241522.0,
 1447194398.0,
 1447312472.0,
 1447312471.0,
 1447312470.0,
 1447373502.0,
 1447305239.0,
 1447194399.0,
 1447261164.0,
 1447219338.0,
 1447373478.0,
 1447373501.0,
 1447309595.0,
 1447211156.0,
 1447394302.0,
 1447403135.0,
 1447403223.0,
 1447373499.0,
 1447266970.0,
 1447373521.0,
 1447304795.0,
 1447304801.0,
 1447312469.0,
 1447373519.0,
 1447229000.0,
 1447229004.0,
 1447304800.0,
 1447373520.0,
 1447261172.0,
 1447229003.0,
 1447304794.0,
 1447373517.0,
 1447373518.0,
 1447304797.0,
 1447229002.0,
 1447373516.0,
 1447229005.0,
 1447304796.0,
 1447194397.0,
 1447229001.0,
 1447373462.0,
 1447194394.0,
 1447194396.0,
 1447194395.0,
 1447304798.0,
 1447304799.0,
 1447373477.0,
 1447305016.0,
 1447373463.0,
 1447390898.0,
 1447373500.0,
 1447389209.0,
 1447219336.0,
 1447261163.0,
 1447219335.0,
 1447241517.0,
 1447241518.0,
 1447398965.0,
 1447373493.0,
 1447373512.0,
 1447281463.0,
 1447187564.0,
 1447261159.0,
 1447227122.0,
 1447212629.0,
 1447227124.0,
 1447390892.0,
 1447393110.0,
 1447323825.0,
 1447373483.0,
 1447373509.0,
 1447373469.0,
 1447227123.0,
 1447261158.0,
 1447227125.0,
 1447179661.0,
 1447313161.0,
 1447373425.0,
 1447373449.0,
 1447373459.0,
 1447373457.0,
 1447240822.0,
 1447373458.0,
 1447373460.0,
 1447305226.0,
 1447373522.0,
 1447373523.0,
 1447308930.0,
 1447261160.0,
 1447241509.0,
 1447241511.0,
 1447373514.0,
 1447261161.0,
 1447241507.0,
 1447241513.0,
 1447261162.0,
 1447214659.0,
 1447219887.0,
 1447187237.0,
 1447281391.0,
 1447281390.0,
 1447373494.0,
 1447373466.0,
 1447191649.0,
 1447390897.0,
 1447373504.0,
 1447410717.0,
 1447229203.0,
 1447207594.0,
 1447373495.0,
 1447391442.0,
 1447373489.0,
 1447373511.0,
 1447373490.0,
 1447373513.0,
 1447211434.0,
 1447362503.0,
 1447273023.0,
 1447327828.0,
 1447350150.0,
 1447209354.0,
 1447273038.0,
 1447156286.0,
 1447207801.0,
 1447353640.0,
 1447172090.0,
 1447203522.0,
 1447353624.0,
 1447384077.0,
 1447331098.0,
 1447172061.0,
 1447289953.0,
 1447310383.0,
 1447152287.0,
 1447207802.0,
 1447269304.0,
 1447269278.0,
 1447172088.0,
 1447269269.0,
 1447201494.0,
 1447272973.0,
 1447286377.0,
 1447384052.0,
 1447201524.0,
 1447384055.0,
 1447310390.0,
 1447221387.0,
 1447207820.0,
 1447201517.0,
 1447353629.0,
 1447269353.0,
 1447286292.0,
 1447172041.0,
 1447156283.0,
 1447272984.0,
 1447290014.0,
 1447162260.0,
 1447290012.0,
 1447152289.0,
 1447201512.0,
 1447353625.0,
 1447399905.0,
 1447335401.0,
 1447311716.0,
 1447322708.0,
 1447182396.0,
 1447185194.0,
 1447182387.0,
 1447207513.0,
 1447320602.0,
 1447182386.0,
 1447269478.0,
 1447269480.0,
 1447399908.0,
 1447184600.0,
 1447386506.0,
 1447326639.0,
 1447184597.0,
 1447242879.0,
 1447242878.0,
 1447320603.0,
 1447286436.0,
 1447286435.0,
 1447378806.0,
 1447182405.0,
 1447364749.0,
 1447396881.0,
 1447278503.0,
 1447369945.0,
 1447196785.0,
 1447385927.0,
 1447405875.0,
 1447399899.0,
 1447412842.0,
 1447385918.0,
 1447299630.0,
 1447184611.0,
 1447231050.0,
 1447399900.0,
 1447196787.0,
 1447182372.0,
 1447295077.0,
 1447184608.0,
 1447254398.0,
 1447334666.0,
 1447182400.0,
 1447323148.0,
 1447280406.0,
 1447372039.0,
 1447254397.0,
 1447305783.0,
 1447312169.0,
 1447329265.0,
 1447269476.0,
 1447421844.0,
 1447421255.0,
 1447343381.0,
 1447390884.0,
 1447242880.0,
 1447320329.0,
 1447387536.0,
 1447189600.0,
 1447182388.0,
 1447269474.0,
 1447405842.0,
 1447310423.0,
 1447184603.0,
 1447184602.0,
 1447372038.0,
 1447372031.0,
 1447293053.0,
 1447278507.0,
 1447182404.0,
 1447399903.0,
 1447182406.0,
 1447364735.0,
 1447369944.0,
 1447320651.0,
 1447178352.0,
 1447269475.0,
 1447305206.0,
 1447364747.0,
 1447196784.0,
 1447184610.0,
 1447385926.0,
 1447399902.0,
 1447278508.0,
 1447405876.0,
 1447399898.0,
 1447403212.0,
 1447306817.0,
 1447386267.0,
 1447189599.0,
 1447399901.0,
 1447399907.0,
 1447322709.0,
 1447269513.0,
 1447306129.0,
 1447385917.0,
 1447325918.0,
 1447299631.0,
 1447278502.0,
 1447178198.0,
 1447335402.0,
 1447335403.0,
 1447369943.0,
 1447365153.0,
 1447231053.0,
 1447365154.0,
 1447182376.0,
 1447183196.0,
 1447182379.0,
 1447405827.0,
 1447182373.0,
 1447184605.0,
 1447306134.0,
 1447182883.0,
 1447184588.0,
 1447255583.0,
 1447231072.0,
 1447182882.0,
 1447320586.0,
 1447320592.0,
 1447223804.0,
 1447184604.0,
 1447320595.0,
 1447320606.0,
 1447406958.0,
 1447182401.0,
 1447399914.0,
 1447231073.0,
 1447182884.0,
 1447254391.0,
 1447254392.0,
 1447245217.0,
 1447320583.0,
 1447320594.0,
 1447264574.0,
 1447355119.0,
 1447320588.0,
 1447372037.0,
 1447399904.0,
 1447355123.0,
 1447355124.0,
 1447343380.0,
 1447184598.0,
 1447182389.0,
 1447184589.0,
 1447320587.0,
 1447327907.0,
 1447399913.0,
 1447213260.0,
 1447399915.0,
 1447182390.0,
 1447355337.0,
 1447182886.0,
 1447299610.0,
 1447182885.0,
 1447373231.0,
 1447371388.0,
 1447184599.0,
 1447410408.0,
 1447391027.0,
 1447320591.0,
 1447280413.0,
 1447264573.0,
 1447320585.0,
 1447185192.0,
 1447355120.0,
 1447245218.0,
 1447231074.0,
 1447399911.0,
 1447209042.0,
 1447350179.0,
 1447209043.0,
 1447320593.0,
 1447369942.0,
 1447209554.0,
 1447255430.0,
 1447320590.0,
 1447320584.0,
 1447399912.0,
 1447254105.0,
 1447201699.0,
 1447182385.0,
 1447398732.0,
 1447394819.0,
 1447329266.0,
 1447184607.0,
 1447329261.0,
 1447407856.0,
 1447407857.0,
 1447329259.0,
 1447407859.0,
 1447280418.0,
 1447329260.0,
 1447184592.0,
 1447398733.0,
 1447320707.0,
 1447320666.0,
 1447288728.0,
 1447182382.0,
 1447327976.0,
 1447327960.0,
 1447280416.0,
 1447399910.0,
 1447280415.0,
 1447399909.0,
 1447280409.0,
 1447328001.0,
 1447182378.0,
 1447223803.0,
 1447182399.0,
 1447302712.0,
 1447196781.0,
 1447184609.0,
 1447293694.0,
 1447366429.0,
 1447375270.0,
 1447305210.0,
 1447231052.0,
 1447305207.0,
 1447182375.0,
 1447231051.0,
 1447182374.0,
 1447405877.0,
 1447305209.0,
 1447209092.0,
 1447299629.0,
 1447305208.0,
 1447399906.0,
 1447185191.0,
 1447185193.0,
 1447326510.0,
 1447326509.0,
 1447254393.0,
 1447269479.0,
 1447385928.0,
 1447182377.0,
 1447196786.0,
 1447405878.0,
 1447326508.0,
 1447396858.0,
 1447280507.0,
 1447178241.0,
 1447352013.0,
 1447264570.0,
 1447264569.0,
 1447214824.0,
 1447308839.0,
 1447214826.0,
 1447414291.0,
 1447286499.0,
 1447328085.0,
 1447214825.0,
 1447350348.0,
 1447371476.0,
 1447235003.0,
 1447237186.0,
 1447329264.0,
 1447329263.0,
 1447330515.0,
 1447330517.0,
 1447168424.0,
 1447330514.0,
 1447365953.0,
 1447304504.0,
 1447348314.0,
 1447373184.0,
 1447365956.0,
 1447373183.0,
 1447348313.0,
 1447334859.0,
 1447388156.0,
 1447304503.0,
 1447365955.0,
 1447373182.0,
 1447348312.0,
 1447334858.0,
 1447365954.0,
 1447348311.0,
 1447373181.0,
 1447388155.0,
 1447388154.0,
 1447348315.0,
 1447365957.0,
 1447330516.0,
 1447327241.0,
 1447339222.0,
 1447288500.0,
 1447288503.0,
 1447360755.0,
 1447282656.0,
 1447339225.0,
 1447327240.0,
 1447339221.0,
 1447360784.0,
 1447339220.0,
 1447339224.0,
 1447360775.0,
 1447327239.0,
 1447288502.0,
 1447214231.0,
 1447288505.0,
 1447282653.0,
 1447214237.0,
 1447288507.0,
 1447282657.0,
 1447327242.0,
 1447288504.0,
 1447339226.0,
 1447214238.0,
 1447288508.0,
 1447288501.0,
 1447214236.0,
 1447360750.0,
 1447339223.0,
 1447282658.0,
 1447360743.0,
 1447308857.0,
 1447308861.0,
 1447308858.0,
 1447308856.0,
 1447308860.0,
 1447308859.0,
 1447200758.0,
 1447381349.0,
 1447200756.0,
 1447381353.0,
 1447282660.0,
 1447327246.0,
 1447381356.0,
 1447327253.0,
 1447327250.0,
 1447327257.0,
 1447282659.0,
 1447381348.0,
 1447200755.0,
 1447327245.0,
 1447327258.0,
 1447381352.0,
 1447327256.0,
 1447308848.0,
 1447327249.0,
 1447327255.0,
 1447308851.0,
 1447381347.0,
 1447381355.0,
 1447327244.0,
 1447381351.0,
 1447327252.0,
 1447327248.0,
 1447381354.0,
 1447308850.0,
 1447327243.0,
 1447200757.0,
 1447381350.0,
 1447327254.0,
 1447327247.0,
 1447327251.0,
 1447282654.0,
 1447308849.0,
 1447356165.0,
 1447288499.0,
 1447282652.0,
 1447295792.0,
 1447214230.0,
 1447327238.0,
 1447236173.0,
 1447236169.0,
 1447282665.0,
 1447327260.0,
 1447236167.0,
 1447334886.0,
 1447214232.0,
 1447334862.0,
 1447334861.0,
 1447308853.0,
 1447214242.0,
 1447236175.0,
 1447236168.0,
 1447334865.0,
 1447236172.0,
 1447236166.0,
 1447327259.0,
 1447288536.0,
 1447214239.0,
 1447282664.0,
 1447288578.0,
 1447327262.0,
 1447334878.0,
 1447236171.0,
 1447308852.0,
 1447214240.0,
 1447334864.0,
 1447288535.0,
 1447334880.0,
 1447308855.0,
 1447282663.0,
 1447334868.0,
 1447334867.0,
 1447334887.0,
 1447236170.0,
 1447282655.0,
 1447334863.0,
 1447327261.0,
 1447282662.0,
 1447334866.0,
 1447288537.0,
 1447236174.0,
 1447282661.0,
 1447308854.0,
 1447330518.0,
 1447187807.0,
 1447187806.0,
 1447214228.0,
 1447282650.0,
 1447288533.0,
 1447339219.0,
 1447214229.0,
 1447282651.0,
 1447356164.0,
 1447388153.0,
 1447301482.0,
 1447327237.0,
 1447288534.0,
 1447194703.0,
 1447282666.0,
 1447388157.0,
 1447282667.0,
 1447219839.0,
 1447327265.0,
 1447167623.0,
 1447327264.0,
 1447327263.0,
 1447167624.0,
 1447327266.0,
 1447339227.0,
 1447339229.0,
 1447339228.0,
 1447339231.0,
 1447214233.0,
 1447214241.0,
 1447339230.0,
 1447388152.0,
 1447282649.0,
 1447308840.0,
 1447327236.0,
 1447214235.0,
 1447308843.0,
 1447214227.0,
 1447327235.0,
 1447308842.0,
 1447214234.0,
 1447327234.0,
 1447308841.0,
 1447308845.0,
 1447288524.0,
 1447308844.0,
 1447288511.0,
 1447308847.0,
 1447288516.0,
 1447308846.0,
 1447168422.0,
 1447356162.0,
 1447187804.0,
 1447295791.0,
 1447339217.0,
 1447187803.0,
 1447339218.0,
 1447295790.0,
 1447295789.0,
 1447187802.0,
 1447356163.0,
 1447187799.0,
 1447295788.0,
 1447187801.0,
 1447356194.0,
 1447208342.0,
 1447200254.0,
 1447211351.0,
 1447191373.0,
 1447208340.0,
 1447208341.0,
 1447164800.0,
 1447262027.0,
 1447336147.0,
 1447336186.0,
 1447399702.0,
 1447336149.0,
 1447399706.0,
 1447167523.0,
 1447343637.0,
 1447261853.0,
 1447383114.0,
 1447257482.0,
 1447156745.0,
 1447230394.0,
 1447370724.0,
 1447156710.0,
 1447300226.0,
 1447164386.0,
 1447373223.0,
 1447165554.0,
 1447219466.0,
 1447179683.0,
 1447241526.0,
 1447230392.0,
 1447399727.0,
 1447192327.0,
 1447382563.0,
 1447313156.0,
 1447156765.0,
 1447323747.0,
 1447317936.0,
 1447302710.0,
 1447346430.0,
 1447367897.0,
 1447133243.0,
 1447409772.0,
 1447266854.0,
 1447144367.0,
 1447283686.0,
 1447257476.0,
 1447206321.0,
 1447227086.0,
 1447165381.0,
 1447156543.0,
 1447185732.0,
 1447267052.0,
 1447361747.0,
 1447293733.0,
 1447212593.0,
 1447156708.0,
 1447227164.0,
 1447288660.0,
 1447293784.0,
 1447216087.0,
 1447171212.0,
 1447288820.0,
 1447354717.0,
 1447240228.0,
 1447394617.0,
 1447353039.0,
 1447230395.0,
 1447265705.0,
 1447188577.0,
 1447188580.0,
 ...]

In [24]:
order_ports.append(order_id)

In [25]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [26]:
clf.predict([[2., 2.]])

array([1])